# customlabel.kv

<CustomLabel>:
    Label:
        text: 'Custom Label'
        size_hint: None, None
        size: self.texture_size
        pos_hint: {'center_x': 0.5, 'center_y': 0.5}

<CustomLabelBox>
    canvas:
        Color:
            rgba: 0, 0.2745, 0.9412, 1
        RoundedRectangle:
            pos: self.pos
            size: self.size
            radius: [(20, 20), (20, 20), (20, 20), (20, 20)]
    size_hint: None, None
    size: self.texture_size
    pos_hint: {'center_x': 0.2, 'top': 0.64}
    